# Commitlint configuration for Conventional Commits
# https://commitlint.js.org/

extends:
  - '@commitlint/config-conventional'

rules:
  # Type must be one of these
  type-enum:
    - 2
    - always
    - - feat      # New feature
      - fix       # Bug fix
      - docs      # Documentation
      - style     # Code style (formatting)
      - refactor  # Code refactor
      - perf      # Performance improvement
      - test      # Tests
      - build     # Build system
      - ci        # CI/CD
      - chore     # Maintenance
      - revert    # Revert commit

  # Scope is optional but if provided must match these
  scope-enum:
    - 2
    - always
    - - auth-service
      - chat-service
      - world-state
      - physics-service
      - script-executor
      - asset-service
      - persistence-service
      - graphics-gateway
      - text-gateway
      - client
      - shared
      - deployment
      - ci
      - docker
      - deps
      - config
      - security
      - migrations

  # Subject case must be lowercase
  subject-case:
    - 2
    - always
    - lowercase

  # Subject must not end with period
  subject-full-stop:
    - 2
    - never
    - '.'

  # Subject must not be empty
  subject-empty:
    - 2
    - never

  # Type must not be empty
  type-empty:
    - 2
    - never

  # Header max length (including type, scope, subject)
  header-max-length:
    - 2
    - always
    - 100

  # Body max line length
  body-max-line-length:
    - 2
    - always
    - 100

  # Footer max line length
  footer-max-line-length:
    - 2
    - always
    - 100
