apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CHANGEME/assignment-W-4.git
    targetRevision: main
    path: deployments/client
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
